"""Basic web UI for the semantic-search RAG pipeline.

Run it with:

    streamlit run app.py

Embeddings are produced by OpenAI (``text-embedding-3-*``) and answers are
generated by Claude. The two panels below let you (1) build/refresh the vector
index from uploaded files or the bundled sample docs, and (2) ask grounded
questions with live-streamed, cited answers.
"""

from __future__ import annotations

import tempfile
from pathlib import Path

import streamlit as st

from rag_pipeline.config import settings
from rag_pipeline.ingest import build_store
from rag_pipeline.pipeline import RAGPipeline
from rag_pipeline.vector_store import VectorStore

st.set_page_config(page_title="Semantic Search RAG", page_icon="🔎", layout="wide")


@st.cache_resource(show_spinner=False)
def load_pipeline(store_path: str, use_hyde: bool) -> RAGPipeline:
    """Load a pipeline from a persisted store (cached across reruns)."""
    return RAGPipeline.from_store(store_path, use_hyde=use_hyde)


# --------------------------------------------------------------------------- #
# Sidebar: configuration + indexing
# --------------------------------------------------------------------------- #
with st.sidebar:
    st.header("⚙️ Configuration")
    st.caption(
        f"**Embeddings:** {settings.embedding_provider} · `{settings.embedding_model}`\n\n"
        f"**Generation:** `{settings.generation_model}` (effort={settings.effort})"
    )

    store_path = st.text_input("Store path", value=settings.store_path)
    top_k = st.slider("Chunks to retrieve (top-k)", 1, 15, settings.top_k)
    use_hyde = st.toggle("HyDE query rewriting", value=False,
                         help="Embed a hypothetical answer instead of the bare question.")

    store_exists = Path(store_path).exists()
    st.markdown(f"**Index status:** {'✅ ready' if store_exists else '⚠️ not built yet'}")

    st.divider()
    st.subheader("📥 Build index")

    uploads = st.file_uploader(
        "Upload documents (.txt, .md, .pdf)",
        type=["txt", "md", "markdown", "rst", "pdf"],
        accept_multiple_files=True,
    )
    use_samples = st.checkbox("Include bundled sample docs", value=not uploads)
    append = st.checkbox("Append to existing index", value=False)

    if st.button("Build / refresh index", type="primary", use_container_width=True):
        paths: list[str] = []
        tmpdir = tempfile.mkdtemp(prefix="rag_upload_")
        for f in uploads or []:
            dest = Path(tmpdir) / f.name
            dest.write_bytes(f.getbuffer())
            paths.append(str(dest))
        if use_samples:
            paths.append("data/sample_docs")

        if not paths:
            st.error("Upload files or tick the sample docs box first.")
        else:
            try:
                with st.spinner("Embedding & indexing…"):
                    existing = VectorStore.load(store_path) if append and store_exists else None
                    store = build_store(paths, store=existing)
                    Path(store_path).parent.mkdir(parents=True, exist_ok=True)
                    store.save(store_path)
                load_pipeline.clear()  # invalidate cached pipeline
                st.success(f"Indexed {len(store)} chunks → {store_path}")
            except Exception as exc:  # surface API/key errors in the UI
                st.error(f"Indexing failed: {exc}")


# --------------------------------------------------------------------------- #
# Main: ask a question
# --------------------------------------------------------------------------- #
st.title("🔎 Semantic Search RAG")
st.caption("OpenAI embeddings · Claude answers · grounded, cited responses")

question = st.text_input("Ask a question about your documents",
                         placeholder="e.g. How does the payments API handle retries?")

if st.button("Ask", type="primary") and question:
    if not Path(store_path).exists():
        st.warning("No index found. Build one from the sidebar first.")
        st.stop()

    try:
        rag = load_pipeline(store_path, use_hyde)
    except Exception as exc:
        st.error(f"Could not load pipeline: {exc}")
        st.stop()

    st.subheader("Answer")
    placeholder = st.empty()
    try:
        tokens, answer = rag.stream_query(question, top_k=top_k)
        streamed = ""
        for delta in tokens:
            streamed += delta
            placeholder.markdown(streamed)
    except Exception as exc:
        st.error(f"Generation failed: {exc}")
        st.stop()

    if answer.citations:
        st.subheader("Sources")
        for c in answer.citations:
            with st.expander(f"[{c.marker}] {c.source}  ·  score {c.score:.3f}"):
                st.write(c.snippet)

    with st.expander(f"🔍 Retrieval trace ({len(answer.retrieved)} chunks)"):
        for i, sc in enumerate(answer.retrieved, 1):
            st.markdown(f"**[{i}] {sc.chunk.source}** — score `{sc.score:.3f}`")
            st.caption(" ".join(sc.chunk.text.split())[:300] + "…")

    if answer.usage:
        u = answer.usage
        st.caption(
            f"tokens · in={u.get('input_tokens', 0)} "
            f"out={u.get('output_tokens', 0)} "
            f"cache_read={u.get('cache_read_input_tokens', 0)}"
        )
